import type { OnboardingStep } from '../types/onboarding';

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: 'welcome',
    target: null,
    title: 'Welcome to Tonic',
    body: 'See how chords work together in any key. This 60-second tour shows you the basics.',
    primaryButton: "Let's Go",
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'center',
  },
  {
    id: 'key-selection',
    target: '#key-scale-select',
    title: 'Choose a Key',
    body: 'Every song is in a key. Select one to see its chords, or keep the current key.',
    primaryButton: 'Keep Current',
    showSkip: true,
    advanceTrigger: 'key-change',
    tooltipPosition: 'bottom',
    hintDelay: 4000,
    hintText: 'Try selecting a different key, or click below',
  },
  {
    id: 'chord-strip',
    target: '.chord-cards-horizontal',
    title: 'Your 7 Chords',
    body: 'These are the chords built from the scale. Roman numerals show their role—uppercase means major, lowercase means minor.',
    primaryButton: 'Got it',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'bottom',
  },
  {
    id: 'play-chord',
    target: '.chord-cards-horizontal',
    title: 'Hear the Harmony',
    body: 'Tap any chord card to hear it. The piano below lights up to show which notes are playing.',
    primaryButton: null,
    showSkip: true,
    advanceTrigger: 'chord-played',
    tooltipPosition: 'bottom',
    hintDelay: 3000,
    hintText: 'Tap a chord above',
  },
  {
    id: 'piano-intro',
    target: '.tablet-piano-container',
    title: 'Play the Piano',
    body: 'The piano is fully playable—tap any key to hear its note!',
    primaryButton: 'Got it',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'top',
  },
  {
    id: 'piano-toggles',
    target: '.piano-floating-controls',
    title: 'Visualize Notes',
    body: "Scale highlights all notes in the current key. Chord shows the selected chord's notes.",
    primaryButton: 'Got it',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'top',
  },
  {
    id: 'play-progression',
    target: '.chord-cards-horizontal',
    title: 'The Hit Progression',
    body: 'Now play: I → V → vi → IV. This four-chord pattern powers countless pop songs.',
    primaryButton: 'Next',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'bottom',
  },
  {
    id: 'variations',
    target: '.chord-card-modifiers',
    title: 'Add Color',
    body: 'Each chord card has variation buttons below—try adding a 7th, maj7, or sus4 for different flavors.',
    primaryButton: 'Got it',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'bottom',
  },
  {
    id: 'borrowed-chords',
    target: '.borrowed-toggle-btn',
    title: 'Borrow Chords',
    body: 'Tap Borrowed to reveal chords from outside this key—great for unexpected harmonic colors.',
    primaryButton: 'Got it',
    showSkip: true,
    advanceTrigger: 'button',
    tooltipPosition: 'bottom',
  },
  {
    id: 'explore',
    target: null,
    title: "You're Ready",
    body: "You've got the basics! Experiment with different keys, chords, and sounds. Replay this tutorial anytime from Settings.",
    primaryButton: 'Start Exploring',
    showSkip: false,
    advanceTrigger: 'button',
    tooltipPosition: 'center',
  },
];

export const PROGRESSION_TARGET_CHORDS = ['I', 'V', 'vi', 'IV'] as const;

export const PROGRESSION_SONG = {
  lyric: 'Just a small town girl...',
  song: "Don't Stop Believin'",
  artist: 'Journey',
} as const;
